version: "3.8"

services:

  accounts:
    image: tpgitz/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - tpgitz-network
    
  loans:
    image: tpgitz/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - tpgitz-network
    
  cards:
    image: tpgitz/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - tpgitz-network
    
networks:
  tpgitz-network: